In [1]:
import torch
torch.__version__

'2.3.1'

In [2]:
scalar = torch.tensor(7);
print(scalar)

tensor(7)


In [3]:
scalar.item()

7

In [9]:
vector = torch.tensor([7, 7])
print(vector,vector.ndim,
vector.shape)


tensor([7, 7]) 1 torch.Size([2])


In [6]:
matrix = torch.tensor([
    [7,8],[9,10]
])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
print(matrix.ndim,
matrix.ndim,
matrix.shape)

2 2 torch.Size([2, 2])


In [10]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi
